# Generated by Django 2.2.10 on 2020-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200304_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestoneyear',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
