# Generated by Django 2.2.10 on 2020-03-04 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200304_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='baseline',
        ),
        migrations.AlterField(
            model_name='logdata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogDataCategory', to='api.LogCategory'),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogDataSubCategory', to='api.LogSubCategory'),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogDataYear', to='api.MilestoneYear'),
        ),
    ]
