# Generated by Django 2.2.10 on 2020-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200304_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'Number'), (1, 'Funds'), (2, 'Percentage')], default=0),
        ),
    ]
