# Generated by Django 2.2.10 on 2020-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_logdata_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsubcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='logdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='planned_afp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='achieved',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='planned',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
