# Generated by Django 2.2.10 on 2020-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200305_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
