# Generated by Django 2.2.10 on 2020-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200313_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestoneyear',
            name='year',
        ),
        migrations.AddField(
            model_name='milestoneyear',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='milestoneyear',
            name='range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
