# Generated by Django 2.2.10 on 2020-03-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200313_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogCat', to='api.LogCategory'),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogSubCat', to='api.LogSubCategory'),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LogTitle', to='api.Title'),
        ),
        migrations.AlterField(
            model_name='logdata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LogYear', to='api.MilestoneYear'),
        ),
        migrations.AlterField(
            model_name='title',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TitleSubCat', to='api.LogSubCategory'),
        ),
    ]
