# Generated by Django 2.2.10 on 2020-03-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200318_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='planned',
        ),
    ]
