# Generated by Django 2.2.10 on 2020-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_logdata_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='data_type',
            field=models.CharField(choices=[('number', 'Number'), ('budget', 'Budget'), ('percentage', 'Percentage')], default='number', max_length=30),
        ),
    ]
