# Generated by Django 2.2.10 on 2020-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200402_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='unit',
            field=models.CharField(choices=[('pound', 'Pound'), ('rupees', 'Rupees')], default='number', max_length=30),
        ),
    ]
