# Generated by Django 2.2.10 on 2020-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_logdata_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='unit',
            field=models.CharField(blank=True, choices=[('pound', 'Pound'), ('rupees', 'Rupees')], max_length=30, null=True),
        ),
    ]
