# Generated by Django 2.2.10 on 2020-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200402_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='is_related',
            field=models.BooleanField(default=False),
        ),
    ]
