# Generated by Django 2.2.10 on 2020-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_logdata_is_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestoneyear',
            name='period',
            field=models.CharField(blank=True, choices=[('y1', 'Year 1'), ('y2', 'Year 2'), ('y3', 'Year 3'), ('y4', 'Year 4'), ('y5', 'Year 5'), ('y6', 'Year 6'), ('y7', 'Year 7'), ('y8', 'Year 8'), ('y9', 'Year 9'), ('y10', 'Year 10')], max_length=30, null=True),
        ),
    ]
