# Generated by Django 2.2.10 on 2020-05-17 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200409_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='automation',
            name='partner_institution',
        ),
        migrations.CreateModel(
            name='AutomationPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, default=0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0, null=True)),
                ('beneficiary', models.IntegerField(blank=True, default=0, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AutoPartner', to='api.Partner')),
            ],
        ),
        migrations.AddField(
            model_name='automation',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Partner', to='api.Partner'),
        ),
    ]
