# Generated by Django 2.2.10 on 2020-05-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200517_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partner', to='api.Partner'),
        ),
    ]
