# Generated by Django 2.2.10 on 2020-05-17 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200517_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationpartner',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutoPartner', to='api.Partner'),
        ),
    ]
