# Generated by Django 2.2.10 on 2020-05-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_district_n_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartnerAuto', to='api.AutomationPartner'),
        ),
    ]
