# Generated by Django 2.2.10 on 2020-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200523_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
