# Generated by Django 2.2.10 on 2020-06-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_financialprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLiteracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(blank=True, choices=[('Microfinance Institutions', 'Microfinance Institutions'), ('Commercial Bank and Other Partners', 'Commercial Bank and Other Partners')], max_length=200, null=True)),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('single_count', models.IntegerField(blank=True, default=0, null=True)),
                ('partner_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartnerFinancial', to='api.Partner')),
                ('program_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProgramFinancial', to='api.FinancialProgram')),
            ],
        ),
    ]
