# Generated by Django 2.2.10 on 2020-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_financialliteracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcategory',
            name='yearname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
