# Generated by Django 2.2.10 on 2020-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_logcategory_yearname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(blank=True, max_length=500, null=True)),
                ('investment_primary', models.CharField(blank=True, max_length=500, null=True)),
                ('investment_secondary', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
