# Generated by Django 2.2.10 on 2020-06-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type',
            field=models.CharField(blank=True, choices=[('Microfinance Institutions', 'Microfinance Institutions'), ('Commercial Bank and Other Partners', 'Commercial Bank and Other Partners')], max_length=200, null=True),
        ),
    ]
