# Generated by Django 2.2.10 on 2020-06-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200624_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leverage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
