# Generated by Django 2.2.10 on 2020-06-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_project_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leverage',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
