# Generated by Django 2.2.10 on 2020-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200629_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scf_funds',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
