# Generated by Django 2.2.10 on 2020-07-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_product_productprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
