# Generated by Django 2.2.10 on 2020-07-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200701_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprocess',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productprocess',
            name='product_category',
        ),
        migrations.AlterField(
            model_name='logdata',
            name='data_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
