# Generated by Django 2.2.10 on 2020-07-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_quarter', models.CharField(blank=True, max_length=500, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('yearly_fund', models.FloatField(blank=True, null=True)),
                ('social_security_recipients', models.IntegerField(blank=True, null=True)),
                ('yearly_social_security_payment', models.FloatField(blank=True, null=True)),
                ('nearest_branch_distance', models.FloatField(blank=True, null=True)),
                ('communication_landline', models.CharField(blank=True, max_length=500, null=True)),
                ('communication_mobile', models.CharField(blank=True, max_length=500, null=True)),
                ('communication_internet', models.CharField(blank=True, max_length=500, null=True)),
                ('communication_internet_other', models.CharField(blank=True, max_length=500, null=True)),
                ('available_electricity_maingrid', models.CharField(blank=True, max_length=500, null=True)),
                ('available_electricity_micro_hydro', models.CharField(blank=True, max_length=500, null=True)),
                ('nearest_road_location_name', models.CharField(blank=True, max_length=500, null=True)),
                ('nearest_road_distance', models.FloatField(blank=True, null=True)),
                ('nearest_road_type', models.CharField(blank=True, max_length=500, null=True)),
                ('nearest_police_location_name', models.CharField(blank=True, max_length=500, null=True)),
                ('nearest_police_distance', models.FloatField(blank=True, null=True)),
                ('categorisation_by_sakchyam', models.CharField(blank=True, max_length=500, null=True)),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecondDistrict', to='api.District')),
                ('municipality_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecondMunicipality', to='api.Municipality')),
                ('province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SecondProvince', to='api.Province')),
            ],
        ),
    ]
