# Generated by Django 2.2.10 on 2020-07-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_secondarydata_hdi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(blank=True, max_length=500, null=True)),
                ('market_name', models.CharField(blank=True, max_length=500, null=True)),
                ('expansion_driven_by', models.CharField(blank=True, max_length=500, null=True)),
                ('point_service', models.CharField(blank=True, max_length=500, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('g2p_payment', models.CharField(blank=True, max_length=500, null=True)),
                ('demonstration_effect', models.DateField(blank=True, null=True)),
                ('gps_point', models.DateField(blank=True, null=True)),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutDistrict', to='api.District')),
                ('municipality_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutMunicipality', to='api.Municipality')),
                ('partner_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutreachPartner', to='api.Partner')),
                ('province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutProvince', to='api.Province')),
            ],
        ),
    ]
