# Generated by Django 2.2.10 on 2020-07-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_outreach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='demonstration_effect',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='gps_point',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
