# Generated by Django 2.2.10 on 2020-08-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200727_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_innovation', models.CharField(blank=True, max_length=500, null=True)),
                ('achievement_type', models.CharField(blank=True, max_length=500, null=True)),
                ('achieved_number', models.IntegerField(blank=True, null=True)),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MFDistrict', to='api.District')),
                ('municipality_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MFMunicipality', to='api.Municipality')),
                ('partner_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MFPartner', to='api.Partner')),
                ('province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MFProvince', to='api.Province')),
            ],
        ),
    ]
