# Generated by Django 2.2.10 on 2020-08-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_mfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_channel', models.CharField(blank=True, max_length=500, null=True)),
                ('innovation', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_insurance_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_of_insurance', models.FloatField(blank=True, default=0, null=True)),
                ('amount_of_sum_insuranced', models.FloatField(blank=True, default=0, null=True)),
                ('amount_of_claim', models.FloatField(blank=True, default=0, null=True)),
                ('partner_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InPartner', to='api.Partner')),
            ],
        ),
    ]
