# Generated by Django 2.2.10 on 2020-08-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200811_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprocess',
            old_name='partner_type',
            new_name='partner_types',
        ),
    ]
