# Generated by Django 2.2.10 on 2020-08-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20200814_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprocess',
            old_name='partner_types',
            new_name='partner_type',
        ),
    ]
