# Generated by Django 2.2.10 on 2020-08-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200814_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('Microfinance/Cooperative', 'Microfinance/Cooperative'), ('Commercial Banks and Mobile Network Operators', 'Commercial Banks and Mobile Network Operators')], max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='financialliteracy',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('Microfinance/Cooperative', 'Microfinance/Cooperative'), ('Commercial Banks and Mobile Network Operators', 'Commercial Banks and Mobile Network Operators')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DirectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.CharField(choices=[('Microfinance/Cooperative', 'Microfinance/Cooperative'), ('Commercial Banks and Mobile Network Operators', 'Commercial Banks and Mobile Network Operators')], max_length=500)),
                ('direct_links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Payment')),
            ],
        ),
    ]
