# Generated by Django 2.2.10 on 2020-08-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20200821_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
