# Generated by Django 2.2.10 on 2020-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.CharField(choices=[('null', 'null'), ('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('null', 'null'), ('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500)),
                ('indirect_links', models.CharField(choices=[('null', 'null'), ('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], default='null', max_length=500)),
                ('link_with_indirect', models.CharField(choices=[('null', 'null'), ('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], default='null', max_length=500)),
                ('direct_links', models.ManyToManyField(to='api.DirectLink')),
            ],
        ),
    ]
