# Generated by Django 2.2.10 on 2020-08-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_directlink_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='component_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
