# Generated by Django 2.2.10 on 2020-08-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20200824_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='partner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentpartner', to='api.Partner'),
        ),
    ]
