# Generated by Django 2.2.10 on 2020-08-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_payment_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='direct_links',
            field=models.ManyToManyField(blank=True, null=True, to='api.DirectLink'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='indirect_links',
            field=models.CharField(blank=True, choices=[('null', 'null'), ('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='link_with_indirect',
            field=models.CharField(blank=True, choices=[('null', 'null'), ('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='partner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentpartner', to='api.Partner'),
            preserve_default=False,
        ),
    ]
