# Generated by Django 2.2.10 on 2020-08-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20200825_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='partner_id',
        ),
        migrations.AlterField(
            model_name='directlink',
            name='components',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='component',
            field=models.CharField(choices=[('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='indirect_links',
            field=models.CharField(blank=True, choices=[('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='link_with_indirect',
            field=models.CharField(blank=True, choices=[('RTGS', 'RTGS'), ('National Switch', 'National Switch'), ('CSD', 'CSD'), ('Card and Switch System', 'Card and Switch System'), ('PSPs/PSOs', 'PSPs/PSOs'), ('NCHL', 'NCHL'), ('BFIS', 'BFIS'), ('Capital Market Players', 'Capital Market Players')], max_length=500, null=True),
        ),
    ]
