# Generated by Django 2.2.10 on 2020-11-23 08:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20200825_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
