# Generated by Django 2.2.10 on 2020-11-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20201123_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='allocated_beneficiary',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='allocated_budget',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='blb',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='extension_counter',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='female_beneficiary',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='female_percentage',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='municipality_id',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='other_products',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='project_year',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='scf_funds',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='status',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='tablet',
        ),
        migrations.RemoveField(
            model_name='partnership',
            name='total_beneficiary',
        ),
    ]
