# Generated by Django 2.2.10 on 2020-11-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20201123_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='allocated_beneficiary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='allocated_budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='beneficiary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='blb',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='branch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartDistrict', to='api.District'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='extension_counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='female_beneficiary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='female_percentage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='municipality_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartMunicipality', to='api.Municipality'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='other_products',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='partner_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartnerPart', to='api.Partner'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='project_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectPartner', to='api.Project'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='project_year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PartProvince', to='api.Province'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='scf_funds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='tablet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='total_beneficiary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
