# Generated by Django 2.2.10 on 2020-11-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20201123_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='leverage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
