from django.urls import path, include
from dashboard import views

urlpatterns = [
    path('create-user/', views.signup, name='create-user'),
    path('useredit-role/<int:id>', views.usereditrole, name='user-edit-role'),
    path('activate/<int:id>', views.activate_user, name='activate'),
    path('staff/<int:id>', views.staff_user, name='staff'),
    path('main/', views.Dashboard.as_view(), name='main'),
    path('user/', views.UserList.as_view(), name='user'),
    path('role/', views.RoleList.as_view(), name='role'),
    path('add-role/', views.RoleCreate.as_view(), name='add-role'),
    path('edit-role/<int:pk>', views.RoleUpdate.as_view(), name='edit-role'),
    path('assign-role/<int:id>', views.assign_role, name='assign-role'),
    path('changepassword/', views.change_password, name='changepassword'),
    path('log-frame-add/<int:cat>/<int:subcat>', views.LogDataCreate.as_view(), name='log-frame-add'),
    path('logframe-list/<int:id>', views.LogFrameList.as_view(), name='logframe-list'),
    path('logdata-edit/<int:pk>/<int:cat>/<int:subcat>', views.LogDataUpdate.as_view(), name='logdata-edit'),
    path('logdata-delete/<int:pk>/<int:cat>/<int:subcat>', views.LogDataDelete.as_view(), name='logdata-delete'),
    path('logsubcat-add/<int:cat>', views.LogSubCatCreate.as_view(), name='logsubcat-add'),
    path('logsubcat-edit/<int:pk>/<int:cat>', views.LogSubCatUpdate.as_view(), name='logsubcat-edit'),
    path('logsubcat-delete/<int:pk>/<int:cat>', views.LogSubCategoryDelete.as_view(), name='logsubcat-delete'),
    path('payment-delete/<int:pk>', views.PaymentDelete.as_view(), name='payment-delete'),
    path('logsubcat-list/<int:id>', views.LogSubCategoryList.as_view(), name='logsubcat-list'),

    # path('logtitle-add/<int:subcat>', views.LogTitleCreate.as_view(), name='logtitle-add'),
    path('logcat-list/', views.LogCategoryList.as_view(), name='logcat-list'),
    path('logcat-add/', views.LogCategoryCreate.as_view(), name='logcategory-add'),
    path('logcat-edit/<int:pk>', views.LogCategoryUpdate.as_view(), name='logcategory-edit'),
    path('logcat-delete/<int:pk>', views.LogCategoryDelete.as_view(), name='logcategory-delete'),

    path('automation-list/', views.AutomationList.as_view(), name='automation-list'),
    path('outreach-list/', views.OutReachList.as_view(), name='outreach-list'),
    path('payment-list/', views.PaymentList.as_view(), name='payment-list'),
    path('productprocess-list/', views.ProductProcessList.as_view(), name='productprocess-list'),
    path('financialliteracy-list/', views.FinancialLiteracyList.as_view(), name='financialliteracy-list'),
    path('automation-add/', views.AutomationCreate.as_view(), name='automation-add'),
    path('productprocess-add/', views.ProductProcessCreate.as_view(), name='productprocess-add'),
    path('outreach-add/', views.OutReachCreate.as_view(), name='outreach-add'),
    path('financialliteracy-add/', views.FinancialLiteracyCreate.as_view(), name='financialliteracy-add'),
    path('automation-bulk-add/', views.automationBulkCreate, name='automation-bulk-add'),
    path('municipality-bulk-add/', views.MunicipalityBulkCreate, name='municipality-bulk-add'),
    path('automation-partner-bulk-add/', views.AutomationPartnerBulkCreate, name='automation-partner-bulk-add'),
    path('province-bulk-add/', views.ProvinceBulkCreate, name='province-bulk-add'),
    path('district-bulk-add/', views.DistrictBulkCreate, name='district-bulk-add'),
    path('productprocess-bulk-add/', views.productprocessBulkCreate, name='productprocess-bulk-add'),
    path('mfs-bulk-add/', views.mfsBulkCreate, name='mfs-bulk-add'),
    path('insurance-bulk-add/', views.insuranceBulkCreate, name='insurance-bulk-add'),
    path('product-bulk-add/', views.productBulkCreate, name='product-bulk-add'),
    path('financialliteracy-bulk-add/', views.financialliteracyBulkCreate, name='financialliteracy-bulk-add'),
    path('project-bulk-add/', views.projectBulkCreate, name='project-bulk-add'),
    path('partner-bulk-add/', views.partnerBulkCreate, name='partner-bulk-add'),
    path('outreach-bulk-add/', views.outreachBulkCreate, name='outreach-bulk-add'),
    path('partnership-bulk-add/', views.partnershipBulkCreate, name='partnership-bulk-add'),
    path('automation-edit/<int:pk>', views.AutomationEdit.as_view(), name='automation-edit'),
    path('outreach-edit/<int:pk>', views.OutReachEdit.as_view(), name='outreach-edit'),
    path('edit-user/<int:pk>', views.UserEdit, name='user-edit'),
    path('productprocess-edit/<int:pk>', views.ProductProcessEdit.as_view(), name='productprocess-edit'),
    path('automation-delete/<int:pk>', views.AutomationDelete.as_view(), name='automation-delete'),
    path('outreach-delete/<int:pk>', views.OutReachDelete.as_view(), name='outreach-delete'),
    path('productprocess-delete/<int:pk>', views.ProductProcessDelete.as_view(), name='productprocess-delete'),
    path('financialliteracy-delete/<int:pk>', views.FinancialLiteracyDelete.as_view(), name='financialliteracy-delete'),
    path('financialliteracy-edit/<int:pk>', views.FinancialLiteracyEdit.as_view(), name='financialliteracy-edit'),

    # sakchyam partner urls
    path('sakchyam-partners/', views.SakchyamAPartnersList.as_view(), name='sakchyam-partners'),
    path('sakchyam-partners-add/', views.SakchyamAPartnersCreate.as_view(), name='sakchyam-partners-add'),
    path('payment-add/', views.PaymentCreate.as_view(), name='payment-add'),
    path('sakchyam-partners-edit/<int:pk>', views.SakchyamAPartnersEdit.as_view(), name='sakchyam-partners-edit'),
    path('sakchyam-partners-delete/<int:pk>', views.SakchyamPartnersDelete.as_view(), name='sakchyam-partners-delete'),
    path('sakchyam-partners-bulk-add', views.sakchyamPartnerBulkCreate, name='sakchyam-partners-bulk-add'),

    path('sakchyam-project/', views.SakchyamProjectList.as_view(), name='sakchyam-project'),
    path('project-delete/<int:pk>', views.ProjectDelete.as_view(), name='project-delete'),
    path('sakchyam-product/', views.SakchyamProductList.as_view(), name='sakchyam-product'),
    path('product-delete/<int:pk>', views.ProductDelete.as_view(), name='product-delete'),
    path('delete-user/<int:pk>', views.UserDelete.as_view(), name='delete-user'),
    path('project-add/', views.ProjectCreate.as_view(), name='project-add'),
    path('product-add/', views.ProductCreate.as_view(), name='product-add'),
    path('product-edit/<int:pk>', views.ProductEdit.as_view(), name='product-edit'),
    path('project-edit/<int:pk>', views.ProjectEdit.as_view(), name='project-edit'),
    path('province-edit/<int:pk>', views.ProvinceEdit.as_view(), name='province-edit'),
    path('district-edit/<int:pk>', views.DistrictEdit.as_view(), name='district-edit'),
    path('municipalities-edit/<int:pk>', views.MunicipalitiesEdit.as_view(), name='municipalities-edit'),
    path('district-list/', views.DistrictList.as_view(), name='district-list'),
    path('province-list/', views.ProvinceList.as_view(), name='province-list'),
    path('municipalities-list/', views.MunicipalitiesList.as_view(), name='municipalities-list'),
    path('province-add/', views.ProvinceCreate.as_view(), name='province-add'),
    path('district-add/', views.DistrictCreate.as_view(), name='district-add'),
    path('municipalities-add/', views.MunicipalitiesCreate.as_view(), name='municipalities-add'),
    path('milestone-year-add/', views.MilestoneYearCreate.as_view(), name='milestone-year-add'),
    path('district-delete/<int:pk>', views.DistrictDelete.as_view(), name='district-delete'),
    path('province-delete/<int:pk>', views.ProvinceDelete.as_view(), name='province-delete'),
    path('municipalities-delete/<int:pk>', views.MunicipalitiesDelete.as_view(), name='municipalities-delete'),

    path('financial_program-list/', views.FinancialProgramList.as_view(), name='financial_program-list'),
    path('automation_partners-list/', views.AutomationPartnersList.as_view(), name='automation_partners-list'),

    path('financial_program-delete/<int:pk>', views.FinancialProgramDelete.as_view(), name='project-delete'),

    path('automation_partners-delete/<int:pk>', views.AutomationPartnersDelete.as_view(), name='project-delete'),

    path('financial_program-edit/<int:pk>', views.FinancialProgramEdit.as_view(), name='financial_program-edit'),
    path('payment-edit/<int:pk>', views.PaymentEdit.as_view(), name='payment-edit'),

    path('automation_partners-edit/<int:pk>', views.AutomationPartnersEdit.as_view(), name='automation_partners-edit'),

    path('financial_program-add/', views.FinancialProgramCreate.as_view(), name='financial_program-add'),

    path('automation_partners-add/', views.AutomationPartnersCreate.as_view(), name='automation_partners-add'),

    path('mfs-list/', views.MfsList.as_view(), name='mfs-list'),
    path('insurance-list/', views.InsuranceList.as_view(), name='insurance-list'),
    path('secondary_data-list/', views.SecondaryDataList.as_view(), name='secondary_data-list'),

    path('mfs-delete/<int:pk>', views.MfsDelete.as_view(), name='mfs-delete'),
    path('insurance-delete/<int:pk>', views.InsuranceDelete.as_view(), name='insurance-delete'),
    path('secondary_data-delete/<int:pk>', views.SecondaryDataDelete.as_view(), name='secondary_data-delete'),

    path('mfs-edit/<int:pk>', views.MfsEdit.as_view(), name='mfs-edit'),
    path('insurance-edit/<int:pk>', views.InsuranceEdit.as_view(), name='insurance-edit'),
    path('secondary_data-edit/<int:pk>', views.SecondaryDataEdit.as_view(), name='secondary_data-edit'),

    path('mfs-add/', views.MfsCreate.as_view(), name='mfs-add'),
    path('insurance-add/', views.InsuranceCreate.as_view(), name='insurance-add'),
    path('secondary_data-add/', views.SecondaryDataCreate.as_view(), name='secondary_data-add'),

    path('partnership-list/', views.PartnershipList.as_view(), name='partnership-list'),
    path('partnership-add/', views.PartnershipCreate.as_view(), name='partnership-add'),
    path('partnership-edit/<int:pk>', views.PartnershipEdit.as_view(), name='partnership-edit'),
    path('partnership-delete/<int:pk>', views.PartnershipDelete.as_view(), name='partnership-delete'),
    path('programme-bulk-add', views.programmeBulkCreate, name='programme-bulk-create'),
    path('secondarydata-bulk-add', views.secondarydataBulkCreate, name='secondary-bulk-create')

]
