from django.urls import path, include
from api import views
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('logframe/log-category', views.LogCategoryViewSet.as_view({'get': 'list'}), name='log-category'),
    path('logframe/log-subcategory', views.LogSubCategoryViewSet.as_view({'get': 'list'}), name='log-subcategory'),
    path('logframe/milestone-year', views.MilestoneYearViewSet.as_view({'get': 'list'}), name='milestone-year'),
    path('logframe/log-data', views.LogDataViewSet.as_view({'get': 'list'}), name='log-data'),
    path('logframe/logFrame-data', views.LogDataAlternativeViewSet.as_view({'get': 'list'}), name='logFrame-data'),
    path('logframe/logFrameSingle-data', views.LogDataSingle.as_view({'get': 'list'}), name='logFrameSingle-data'),
    path('token/login/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('token/user-permission/', views.UserPermission.as_view({'get': 'list'}), name='user-permission'),
    path('automation/automation-data/', views.AutomationViewSet.as_view({'get': 'list'}), name='automation'),
    path('automation/table-data/', views.AutomationDataTable.as_view({'get': 'list'}),
         name='table-data'),
    path('automation/timeline/', views.AutomationTimeline.as_view({'get': 'list'}),
         name='timeline'),
    path('automation/map-data/', views.AutomationDataMap.as_view({'get': 'list'}),
         name='map-data'),
    path('automation/automation-all/', views.AutomationDataAll.as_view({'get': 'list'}),
         name='automation-all'),
    path('automation/automation-partner/', views.AutomationDataPartner.as_view({'get': 'list'}),
         name='automation-partner'),
    path('adminlevel/province/', views.ProvinceViewSet.as_view({'post': 'list'}), name='province'),
    path('adminlevel/district/', views.DistrictViewSet.as_view({'post': 'list'}), name='district'),
    path('adminlevel/municipality/', views.MunicipalityViewSet.as_view({'post': 'list'}), name='municipality'),
    path('financial/program/', views.FinancialProgramApi.as_view({'get': 'list'}), name='program'),
    path('financial/all-data/', views.FinancialLiteracyApi.as_view({'get': 'list'}), name='all-data'),
    path('financial/partner/', views.FinancialPartnerApi.as_view({'get': 'list'}), name='financial-partner'),
    path('project/project/', views.ProjectApi.as_view({'post': 'list'}), name='project'),
    path('product/product/', views.ProductApi.as_view({'get': 'list'}), name='product'),
    path('partner/partner/', views.PartnerApi.as_view({'get': 'list'}), name='partner'),
    path('product-process/process/', views.ProductProcessApi.as_view({'get': 'list'}), name='process'),
    path('partnership/partnership-all/', views.PartnershipApi.as_view({'get': 'list'}), name='partnership-all'),
    path('partnership/partnership-filter/', views.PartnershipFilter.as_view({'post': 'list'}),
         name='partnership-filter'),
    path('partnership/partnership-investment/', views.InvestmentApi.as_view({'get': 'list'}),
         name='partnership-investment'),
    path('partnership/radial/', views.PartnershipRadial.as_view({'get': 'list'}),
         name='radial'),
    path('partnership/radar/', views.PartnershipRadar.as_view({'get': 'list'}),
         name='radial'),
    path('partnership/sankey/', views.InvestmentSankey.as_view({'get': 'list'}),
         name='sankey'),
    path('partnership/overview/', views.PartnershipOverview.as_view({'get': 'list'}),
         name='overview'),
    path('partnership/map-data/', views.PartnershipMap.as_view({'get': 'list'}),
         name='map-data'),
    path('process-product/secondary-data/', views.SecondaryViewSet.as_view({'get': 'list'}), name='secondary-data'),

]
